### ISSUE TITLE
Wish: including A/D converter

### ISSUE THREAD

**Issue by ricki-z** [Naesstrom/Airrohr-kit#3]
@Naesstrom : Do you think it's possible to include a place for an ADS1115 and 4 pins for analogue input? We are working on an acoustic sensor and a NO2 sensor that both have analogue output.

Rajko from Luftdaten.info

**Comment by Naesstrom** [comment]
First of all I'm sorry for the late reply!
I'll see, shouldn't be impossible :D

**Comment by Naesstrom** [comment]
@ricki-z something like this?
![image](https://user-images.githubusercontent.com/6575206/48770824-f057e180-ecbf-11e8-99d4-aedd8712614e.png)

**Comment by Naesstrom** [comment]
I just kept going and managed to add one to the NodeMCU version to, now it works for both V1, V2 and V3 in the same board
![image](https://user-images.githubusercontent.com/6575206/48773415-94915680-ecc7-11e8-9152-45ea2bde010f.png)

**Comment by ricki-z** [comment]
@Naesstrom Thank you. We were working on a noise sensor, for which we are using the A/D converter. But this that extra piece of hardware a pcb is much better than our floating wiring.

**Comment by Naesstrom** [comment]
ADS1115 is now added to all versions of the PCB
